### ISSUE TITLE
Highlight shortest path in UI

### ISSUE THREAD

**Issue by mcaleb808** [mcaleb808/labyrinth-escape#15]
### Tasks:

- [x] Update the UI to change the background color of the cells in the shortest path.
- [x] Test the highlighting feature with various labyrinth inputs.
- [x] Commit the changes and push to GitHub.
