### ISSUE TITLE
Refactor Home component by splitting into smaller components

### ISSUE THREAD

**Issue by mcaleb808** [mcaleb808/labyrinth-escape#19]
### Tasks:

- [x] Create LabyrinthGrid component.
- [x]  Create ControlPanel component.
- [ ]  Refactor Home component.
- [ ]  Test refactored components.
- [x]  Commit and push changes.
