### ISSUE TITLE
Set Up GitHub Actions for CI/CD

### ISSUE THREAD

**Issue by mcaleb808** [mcaleb808/labyrinth-escape#4]
### Tasks:

- [x] Create .github/workflows/ci.yml for GitHub Actions.
- [x]  Configure the workflow to run tests using Jest.
- [x] Add the CI/CD status badge to the README.
- [x] Commit the changes and push to GitHub.
